INSERT INTO filters (id, name) VALUES
( 1, 'Açaí'),
( 2, 'Bebidas'),
( 3, 'Pizza'),
( 4, 'Pastel'),
( 5, 'Comida Japonesa'),
( 6, 'Vegana'),
( 7, 'Sorvetes'),
( 8, 'Salgados'),
( 9, 'Peixes'),
( 10, 'Comida Saudável');

INSERT INTO users (name, last_name, email, password) VALUES
('Rafael', 'Silvestre', 'rafaelsilvestre.183@gmail.com', '$2a$10$K6bDGxYgi9vsMTT.labvXuRnVaCrGmbYsVD1RE9ZeJw/3inIX9TtG');

INSERT INTO permissions (users_id, permissions) VALUES
(1, 0);

INSERT INTO districts (id, name) VALUES
( 1, 'Aeroporto'),
( 2, 'Aeroviario'),
( 3, 'Aldeia do Vale'),
( 4, 'Alice Barbosa'),
( 5, 'AlphaVille Flamboyant'),
( 6, 'Alto da Gloria'),
( 7, 'Alto do Vale'),
( 8, 'Antonio Carlos Pires'),
( 9, 'Asa Branca'),
( 10, 'Bairro da Vitoria'),
( 11, 'Bairro Feliz'),
( 12, 'Barravento'),
( 13, 'Bela Vista'),
( 14, 'Boa Vista'),
( 15, 'Brisas da Mata'),
( 16, 'Buena Vista'),
( 17, 'Bueno'),
( 18, 'Campinas'),
( 19, 'Candida de Morais'),
( 20, 'Capuava'),
( 21, 'Castelo Branco'),
( 22, 'Centro'),
( 23, 'Centro Oeste'),
( 24, 'Chacaras Maria Dilce'),
( 25, 'Cidade Jardim'),
( 26, 'Coimbra'),
( 27, 'Conjunto Vera Cruz'),
( 28, 'Crimeia Leste'),
( 29, 'Crimeia Oeste'),
( 30, 'Emilio Povoa'),
( 31, 'Esplanada do Anicuns'),
( 32, 'Estrela DAlva'),
( 33, 'Faiçalville'),
( 34, 'Finsocial'),
( 35, 'Floresta'),
( 36, 'Funcionarios'),
( 37, 'Garavelo'),
( 38, 'Gentil Meireles'),
( 39, 'Goia'),
( 40, 'Goiania 2'),
( 41, 'Goiania Viva'),
( 42, 'Granja Cruzeiro do Sul'),
( 43, 'Granville'),
( 44, 'Guarema'),
( 45, 'Itamaraca'),
( 46, 'Itatiaia'),
( 47, 'Jao'),
( 48, 'Jardim America'),
( 49, 'Jardim Atlantico'),
( 50, 'jardim Balneario Meia Ponte'),
( 51, 'Jardim Belvedere'),
( 52, 'Jardim Botanico'),
( 53, 'Jardim Brasil'),
( 54, 'Jardim California'),
( 55, 'Jardim Colorado'),
( 56, 'Jardim Curitiba'),
( 57, 'Jardim Diamantina'),
( 58, 'Jardim Europa'),
( 59, 'Jardim Fonte Nova'),
( 60, 'Jardim Goias'),
( 61, 'Jardim Guanabara'),
( 62, 'Jardim Ipe'),
( 63, 'Jardim Itaipu'),
( 64, 'Jardim Liberdade'),
( 65, 'Jardim Nova Esperança'),
( 66, 'Jardim Novo Mundo'),
( 67, 'Jardim Planalto'),
( 68, 'Jardim Pompeia'),
( 69, 'Jardim Primavera'),
( 70, 'Jardim Sao Jose'),
( 71, 'Jardim Vila Boa'),
( 72, 'Jardins do Cerrado'),
( 73, 'Joao Paulo 2'),
( 74, 'Joao Vaz'),
( 75, 'Lorena Park'),
( 76, 'Madre Germana 2'),
( 77, 'Mansoes Goianas'),
( 78, 'Marechal Rondon'),
( 79, 'Marista'),
( 80, 'Monte Pascoal'),
( 81, 'Monte Verde'),
( 82, 'Morada do Sol'),
( 83, 'Murumbi'),
( 84, 'Negrao de Lima'),
( 85, 'Norte Ferroviario'),
( 86, 'Nova Suiçaa'),
( 87, 'Nova Vila'),
( 88, 'Novo Horizonte'),
( 89, 'Novo Planalto'),
( 90, 'Oeste'),
( 91, 'Orlando de Morais'),
( 92, 'Panorama Parque'),
( 93, 'Parque Amazonia'),
( 94, 'Parque Anhanguera'),
( 95, 'Parque Atheneu'),
( 96, 'Parque das Flores'),
( 97, 'Parque das Nações'),
( 98, 'Parque Eldorado Oeste'),
( 99, 'Parque Flamboyant'),
( 100, 'Parque Industrial Joao Braz'),
( 101, 'Parque das Laranjeiras'),
( 102, 'Parque Oeste Industrial'),
( 103, 'Parque Tremendao'),
( 104, 'Pedro Ludovico'),
( 105, 'Perim'),
( 106, 'Prive Atlantico'),
( 107, 'Progresso'),
( 108, 'Quebra Caixote'),
( 109, 'Real Conquista'),
( 110, 'Recanto das Minas Gerais'),
( 111, 'Recando do Bosque'),
( 112, 'Residencial Balneario'),
( 113, 'Residencial das Acacias'),
( 114, 'Residencial Guanabara'),
( 115, 'Residencial Italia'),
( 116, 'Residencial Maringa'),
( 117, 'Rodoviario'),
( 118, 'Santa Genoveva'),
( 119, 'Santo Hilario'),
( 120, 'Sao Carlos'),
( 121, 'Sao Domingos'),
( 122, 'Sao Francisco'),
( 123, 'Sao Judas Tadeu'),
( 124, 'Senador Albino Boaventura'),
( 125, 'Serrinha'),
( 126, 'Solange Park'),
( 127, 'Solar Ville'),
( 128, 'Sul'),
( 129, 'Uniao'),
( 130, 'Universitario'),
( 131, 'Urias Magalhaes'),
( 132, 'Vale dos Sonhos'),
( 133, 'Vila Canaa'),
( 134, 'Vila Multirao'),
( 135, 'Vila Nossa Senhora Aparecida'),
( 136, 'Vila Nova'),
( 137, 'Vila Pedroso'),
( 138, 'Vila Redencao'),
( 139, 'Vila Roriz'),
( 140, 'Vila Rosa'),
( 141, 'Vila Santa Helena');